#阿里云key——id
access_key_id: ""
#阿里云secret
access_secret: ""
#阿里云操作地域参数默认北京 https://www.alibabacloud.com/help/zh/doc-detail/40654.htm"
region_id: "cn-beijing"
#获取公网ip的域名,链接可能会挂掉需要更换
get_ip_url: https://ipw.cn/api/ip/myip
